version: "3.8"

services:

  mapstore:
    build:
      dockerfile: ./tests/DockerfileMapStoreTest
      args:
        MAPSTORE_WEBAPP_SRC: "/host/drop/path/mapstore.war"

  sut:
    build:
      context: ./tests/
      dockerfile: Dockerfile
    command: dockerize -wait tcp://postgres:5432 -wait tcp://mapstore:8080 -timeout 20s
    container_name: sutms
    depends_on:
      - postgres
      - mapstore
      - proxy
    networks:
      - mapstore-network