throwErrorOnExtraParameters: true
transparentTileErrorColor: 'rgba(78, 78, 255, 125)'
opaqueTileErrorColor: 'rgba(255, 155, 155, 0)'

templates:
  A4_no_legend: !template
    reportTemplate: report.jrxml
    attributes:
      title: !string
        default: 'Countries'
      map: !map
        maxDpi: 400
        width: 535
        height: 500
    processors:
      - !reportBuilder
        directory: '.'
      - !createMap {}
